# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IN_MAIN": "animal_classes.ipynb",
         "generate_objects": "animal_classes.ipynb",
         "Terrain": "animal_classes.ipynb",
         "Organism": "animal_classes.ipynb",
         "Animal": "animal_classes.ipynb",
         "simple_sheep_radii": "animal_classes.ipynb",
         "simple_sheep_def": "animal_classes.ipynb",
         "SimpleSheep": "animal_classes.ipynb",
         "multi_sheep_radii": "animal_classes.ipynb",
         "multi_sheep_def": "animal_classes.ipynb",
         "MultiSheep": "animal_classes.ipynb",
         "Ecosystem": "animal_classes.ipynb",
         "AnimationHelper": "animation_helper.ipynb",
         "EcoEnv": "ecoenv.ipynb",
         "RADIUS": "perception.ipynb",
         "ORIGIN": "perception.ipynb",
         "Perception": "perception.ipynb",
         "ReflexAgent": "reflex_agent.ipynb",
         "distance": "utility.ipynb",
         "normalize": "utility.ipynb",
         "draw_objects": "utility.ipynb",
         "motion_diagram": "utility.ipynb"}

modules = ["animal_classes.py",
           "animation_helper.py",
           "ecoenv.py",
           "perception.py",
           "reflex_agent.py",
           "utility.py"]

doc_url = "https://LogicalInvestigations.github.io/ecotwins/"

git_url = "https://github.com/LogicalInvestigations/ecotwins/tree/master/"

def custom_doc_links(name): return None
